description: Prepares the repo for a typical CI job

name: Prepare

runs:
  steps:
    - uses: pnpm/action-setup@v4
    - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6
      with:
        cache: pnpm
        node-version: 24.11.0
    - run: pnpm install --frozen-lockfile
      shell: bash
  using: composite
