description: Prepares the repo for a typical CI job

name: Prepare

runs:
  steps:
    - uses: pnpm/action-setup@v4
    - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6
      with:
        cache: pnpm
        node-version: 22.20.0
    - run: pnpm install --frozen-lockfile
      shell: bash
  using: composite
